streets_district1 = [
    "Alexandre de Rhodes", "Huyền Quang", "Nguyễn Hậu", "Phan Kế Bính",
    "Bà Lê Chân", "Huyền Chân Công Chúa", "Nguyễn Huệ", "Phan Liêm",
    "Bến Chương Dương", "Huỳnh Khương Ninh", "Nguyễn Hữu Cảnh", "Phan Ngữ",
    "Bùi Thị Xuân", "Huỳnh Thúc Kháng", "Nguyễn Hữu Cầu", "Phan Tôn",
    "Bùi Viện", "Khánh Hội", "Nguyễn Huy Tự", "Phan Văn Đạt",
    "Cách Mạnh Thánh 8", "Ký Con", "Nguyễn Khắc Nhu", "Phan Văn Trường",
    "Calmette", "Lê Anh Xuân", "Nguyễn Phi Khanh", "Phó Đức Chính",
    "Cao Bá Nhạ", "Lê Công Kiều", "Nguyễn Siêu", "Phùng Khắc Khoan",
    "Cáo Bá Quát", "Lê Duẩn", "Nguyễn Thái Bình", "Sương Nguyệt Ánh",
    "Cây Điệp", "Lê Lai", "Nguyễn Thái Học", "Thạch Thị Thanh",
    "Chu Mạnh Chinh", "Lê Lợi", "Nguyễn Thành Ý", "Thái Văn Lung",
    "Cô Bắc", "Lê Thánh Tôn", "Nguyễn Thị Lựu", "Thi Sách",
    "Cô Giang", "Lê Thị Hồng Gấm", "Nguyễn Thị Mình Khai", "Thủ Khoa Huân",
    "Cống Quỳnh", "Lê Thị Riêng", "Nguyễn Thị Nghĩa", "Tôn Đức Thắng",
    "Công Trường Lam Sơn", "Lê Văn Hưu", "Nguyễn Thiện Thuật", "Tôn Thất Đạm",
    "Công Trường Mê Linh", "Lương Hữu Khánh", "Nguyễn Thiệp", "Tôn Thất Thiệp",
    "Công Trường Paris", "Lưu Văn Lang", "Nguyễn Trãi", "Tôn Thất Tùng",
    "Đặng Dung", "Lý Chiến Thắng", "Nguyễn Văn Bình", "Trần Cao Vân",
    "Đặng Tất", "Lý Thái Tổ", "Nguyễn Văn Chiêm", "Trần Đình Xu",
    "Đặng Thị Nhu", "Lý Văn Phức", "Nguyễn Văn Cừ", "Trần Hưng Đạo",
    "Đặng Trần Côn", "Mã Lộ", "Nguyễn Văn Đượm", "Trần Khắc Chân",
    "Đề Thám", "Mạc Đĩnh Chi", "Nguyễn Văn Giai", "Trần Nhật Duật",
    "Điện Biên Phủ", "Mặc Thị Bưởi", "Nguyễn Văn Nghĩa", "Trần Quang Khải",
    "Đinh Công Tránh", "Mai Thị Lựu", "Nguyễn Văn Nguyên", "Trần Quốc Toản",
    "Đông Du", "Ngô Đức Kế", "Nguyễn Văn Thủ", "Trịnh Văn Cấn",
    "Đồng Khởi", "Ngô Quyền", "Nguyễn Văn Tráng", "Trịnh Văn Cẩn",
    "Hai Bà Trưng", "Ngô Văn Năm", "Nguyễn Văn Trỗi", "Trương Định",
    "Hải Triều", "Nguyễn An Ninh", "Nguyễn Văn Thủ", "Trương Hán Siêu",
    "Hàm Nghi", "Nguyễn Bỉnh Khiêm", "Phạm Hồng Thái", "Võ Thị Sáu",
    "Hồ Hảo Hớn", "Nguyễn Công Chứ", "Phạm Ngọc Thạch", "Võ Văn Kiệt",
    "Hồ Huấn Nghiệp", "Nguyễn Cư Trinh", "Phạm Ngũ Lão", "Vỗ Văn Tần",
    "Hồ Tùng Mậu", "Nguyễn Cửu Vân", "Phạm Viết Chánh", "Yersin",
    "Hòa Mỹ", "Nguyễn Đình Chiểu", "Phan Bội Châu",
    "Hoàng Sa", "Nguyễn Du", "Phan Chu Chinh"
]
streets_district2 = [
    "An Phú", "Đường số 19", "Đường số 55", "Nguyễn Duy Hiệu",
    "An Phú - An Khánh", "2 Đường số 2", "Đường số 57", "Nguyễn Duy Trinh",
    "Bát Nàn", "Đường số 20", "Đường số 58", "Nguyễn Hoàng",
    "Bình Minh", "Đường số 21", "Đường số 59", "Nguyễn Quý Cảnh",
    "Bình Trưng", "Đường số 22", "Đường số 6", "Nguyễn Thị Định",
    "Bình Trưng Đông", "Đường số 23", "Đường số 60", "Nguyễn Trọng Quản",
    "Bùi Tá Hán", "Đường số 24", "Đường số 61", "Nguyễn Trung Nguyệt",
    "Đại lộ Đông Tây", "Đường số 25", "Đường số 63", "Nguyễn Tư Nghiêm",
    "Đặng Hữu Đông", "Đường số 26", "Đường số 64", "Nguyễn Tuyển",
    "Đặng Hữu Phố", "Đường số 27", "Đường số 65", "Nguyễn Văn Cừ",
    "Đặng Tiến Đông", "Đường số 28", "Đường số 66", "Nguyễn Văn Giai",
    "Đỗ Quang", "Đường số 29", "Đường số 7", "Nguyễn Văn Giáp",
    "Đỗ Xuân Hợp", "Đường số 3", "Đường số 8", "Nguyễn Văn Hưởng",
    "Đoàn Hữu Trưng", "Đường số 30", "Đường số 8B", "Nguyễn Văn Kỉnh",
    "Đường 37A khu C", "Đường số 31", "Đường số 9", "Nguyễn Văn Luông",
    "Đường A", "Đường số 32", "Đường số 9B", "Quốc Hương",
    "Đường A4", "Đường số 33", "Dương Văn An", "Song Hành",
    "Đường C2", "Đường số 34", "Giang Văn Minh", "Tạ Hiện",
    "Đường D2", "Đường số 35", "Giao Hoà", "Thái Thuận",
    "Đường E", "Đường số 36", "Huy Hoàng", "Thạnh Mỹ Lợi",
    "Đường G", "2 Đường số 37", "Lê Đình Quân", "Thảo Điền",
    "Đường H", "Đường số 38", "Lê Hữu Kiều", "Thế Kỷ",
    "Đường số 1", "Đường số 39", "Lê Thước", "Thích Mật Thể",
    "Đường số 10", "Đường số 4", "Lê Văn Miến", "Tống Hữu Định",
    "Đường số 10F", "Đường số 40", "Lê Văn Thịnh", "Trần Lựu",
    "Đường số 11", "Đường số 41", "Liên Tỉnh Lộ 25B", "Trần Não",
    "Đường số 12", "Đường số 42", "Lương Định Của", "Trần Ngọc Diện",
    "Đường số 13", "Đường số 43", "Ngô Quang Huy", "Trịnh Khắc Lập",
    "Đường số 14", "Đường số 44", "Nguyễn Bá Huân", "Trúc Đường",
    "Đường số 15", "Đường số 46", "Nguyễn Bá Lân", "Trương Gia Mô",
    "Đường số 16", "Đường số 47", "Nguyễn Cừ", "Trương Văn Bang",
    "Đường số 17", "Đường số 48", "Nguyễn Cư Dĩ", "Võ Trường Toản",
    "Đường số 17A", "Đường số 49B", "Nguyễn Đăng Giai", "Vũ Tông Phan",
    "Đường số 17B", "2 Đường số 5", "Nguyễn Đình Chiểu", "Xa Lộ Hà Nội",
    "Đường số 18", "Đường số 54", "Nguyễn Đôn Tiết", "Xuân Thủy"
]
streets_district3 = [
    "An Phú", "Đường số 19", "Đường số 55", "Nguyễn Duy Hiệu",
    "An Phú - An Khánh", "2 Đường số 2", "Đường số 57", "Nguyễn Duy Trinh",
    "Bát Nàn", "Đường số 20", "Đường số 58", "Nguyễn Hoàng",
    "Bình Minh", "Đường số 21", "Đường số 59", "Nguyễn Quý Cảnh",
    "Bình Trưng", "Đường số 22", "Đường số 6", "Nguyễn Thị Định",
    "Bình Trưng Đông", "Đường số 23", "Đường số 60", "Nguyễn Trọng Quản",
    "Bùi Tá Hán", "Đường số 24", "Đường số 61", "Nguyễn Trung Nguyệt",
    "Đại lộ Đông Tây", "Đường số 25", "Đường số 63", "Nguyễn Tư Nghiêm",
    "Đặng Hữu Đông", "Đường số 26", "Đường số 64", "Nguyễn Tuyển",
    "Đặng Hữu Phố", "Đường số 27", "Đường số 65", "Nguyễn Văn Cừ",
    "Đặng Tiến Đông", "Đường số 28", "Đường số 66", "Nguyễn Văn Giai",
    "Đỗ Quang", "Đường số 29", "Đường số 7", "Nguyễn Văn Giáp",
    "Đỗ Xuân Hợp", "Đường số 3", "Đường số 8", "Nguyễn Văn Hưởng",
    "Đoàn Hữu Trưng", "Đường số 30", "Đường số 8B", "Nguyễn Văn Kỉnh",
    "Đường 37A khu C", "Đường số 31", "Đường số 9", "Nguyễn Văn Luông",
    "Đường A", "Đường số 32", "Đường số 9B", "Quốc Hương",
    "Đường A4", "Đường số 33", "Dương Văn An", "Song Hành",
    "Đường C2", "Đường số 34", "Giang Văn Minh", "Tạ Hiện",
    "Đường D2", "Đường số 35", "Giao Hoà", "Thái Thuận",
    "Đường E", "Đường số 36", "Huy Hoàng", "Thạnh Mỹ Lợi",
    "Đường G", "2 Đường số 37", "Lê Đình Quân", "Thảo Điền",
    "Đường H", "Đường số 38", "Lê Hữu Kiều", "Thế Kỷ",
    "Đường số 1", "Đường số 39", "Lê Thước", "Thích Mật Thể",
    "Đường số 10", "Đường số 4", "Lê Văn Miến", "Tống Hữu Định",
    "Đường số 10F", "Đường số 40", "Lê Văn Thịnh", "Trần Lựu",
    "Đường số 11", "Đường số 41", "Liên Tỉnh Lộ 25B", "Trần Não",
    "Đường số 12", "Đường số 42", "Lương Định Của", "Trần Ngọc Diện",
    "Đường số 13", "Đường số 43", "Ngô Quang Huy", "Trịnh Khắc Lập",
    "Đường số 14", "Đường số 44", "Nguyễn Bá Huân", "Trúc Đường",
    "Đường số 15", "Đường số 46", "Nguyễn Bá Lân", "Trương Gia Mô",
    "Đường số 16", "Đường số 47", "Nguyễn Cừ", "Trương Văn Bang",
    "Đường số 17", "Đường số 48", "Nguyễn Cư Dĩ", "Võ Trường Toản",
    "Đường số 17A", "Đường số 49B", "Nguyễn Đăng Giai", "Vũ Tông Phan",
    "Đường số 17B", "2 Đường số 5", "Nguyễn Đình Chiểu", "Xa Lộ Hà Nội",
    "Đường số 18", "Đường số 54", "Nguyễn Đôn Tiết", "Xuân Thủy"
]
streets_district4 = [
    "Bến Vân Đồn", "Đường số 19", "Đường số 37", "Hoàng Diệu",
    "Dân Sinh", "Đường số 2", "Đường số 38", "Khánh Hội",
    "Đinh Lễ", "Đường số 20", "Đường số 39", "Lê Quốc Hưng",
    "Đoàn Nhữ Hài", "Đường số 21", "Đường số 4", "Lê Thạch",
    "Đoàn Văn Bơ", "Đường số 22", "Đường số 40", "Lê Văn Linh",
    "Đường số 1", "Đường số 23", "Đường số 41", "Ngô Văn Sở",
    "Đường số 10", "Đường số 24", "Đường số 42", "Nguyễn Hữu Hào",
    "Đường số 10A", "2 Đường số 25", "Đường số 43", "Nguyễn Khoái",
    "Đường số 10B", "Đường số 28", "3 Đường số 45", "Nguyễn Tất Thành",
    "Đường số 10C", "Đường số 29", "Đường số 44", "Nguyễn Thần Hiến",
    "Đường số 11", "Đường số 3", "Đường số 46", "Nguyễn Trường Tộ",
    "Đường số 12", "Đường số 30", "Đường số 47", "Tân Vĩnh",
    "Đường số 12A", "Đường số 31", "Đường số 48", "Tôn Đản",
    "Đường số 12B", "Đường số 32", "Đường số 49", "Tôn Thất Thuyết",
    "Đường số 13", "Đường số 32A", "Đường số 50", "Trương Đình Hợi",
    "Đường số 15", "Đường số 33", "Đường số 6", "Vĩnh Hội",
    "Đường số 16", "Đường số 34", "Đường số 7", "Vĩnh Khánh",
    "Đường số 17", "Đường số 35", "Đường số 8", "Xóm Chiếu",
    "Đường số 18", "Đường số 36", "Đường số 9"
]

streets_district5 = [
    "Trần Tướng Công", "Tân Hàng", "Nguyễn Thị Nhỏ", "Hàm Tử",
    "Trần Tuấn Khải", "Tăng Bạt Hổ", "Nguyễn Thi", "Hải Thượng Lãn Ông",
    "Trần Phú", "Tản Đà", "Nguyễn Kim", "Hà Tôn Quyền",
    "Trần Nhân Tôn", "Tạ Uyên", "Nguyễn Duy Dương", "Gò Công",
    "Trần Hưng Đạo", "Sư Vạn Hạnh", "Nguyễn Chí Thanh", "Gia Phú",
    "Trần Hòa", "Phước Hưng", "Nguyễn Biểu", "Đỗ Văn Sửu",
    "Trần Điện", "Phùng Hưng", "Nguyễn Án", "Đỗ Ngọc Thạch",
    "Trần Chánh Chiếu", "Phù Đổng Thiên Vương", "Nguyễn An Khương", "Đăng Thái Thân",
    "Trần Văn Kiểu", "Phú Hữu", "Ngô Quyền", "Đào Tấn",
    "Tăng Bạt Hổ", "Phú Giáo", "Ngô Nhân Tịnh", "Dương Tử Giang",
    "Tản Đà", "Phú Định", "Ngô Gia Tự", "Chiêu Anh Các",
    "Yết Kiêu", "Phó Cơ Điều", "Nghĩa Thục", "Châu Văn Liêm",
    "Xóm Vôi", "Phan Văn Trị", "Mạc Thiên Tích", "Cao Đạt",
    "Vũ Chí Hiếu", "Phan Văn Khỏe", "Mạc Cửu", "Bùi Hữu Nghĩa",
    "Võ Trường Toản", "Phan Phú Tiên", "Lý Thường Kiệt", "Bãi Sậy",
    "Vạn Tuợng", "Phan Huy Chú", "Lưu Xuân Tín", "Bạch Vân",
    "Vạn Kiếp", "Phạm Hữu Chí", "Lương Nhữ Học", "Bà Triệu",
    "Trịnh Hoài Đức", "Phạm Đôn", "Lê Hồng Phong", "An Dương Vương",
    "Triệu Quang Phục", "Phạm Bân", "Lão Tử", "An Điềm",
    "Trần Xuân Hòa", "Nhiêu Tâm", "Ký Hòa", "An Bình",
    "Trang Tử", "Nguyễn Văn Đừng", "Kim Biên", "Võ Trường Toản",
    "Tống Duy Tân", "Nguyễn Tri Phương", "Hưng Long", "Yết Kiêu",
    "Tân Thành", "Nguyễn Trãi", "Huỳnh Mẫn Đạt", "Hồng Bàng",
    "Tân Hưng", "Nguyễn Thời Trung", "Hùng Vương", "Học Lạc"
]
streets_district6 = [
    "An Dương Vương", "Đường số 15", "Đường số 52", "Nguyễn Hữu Thận",
    "Bà Hom", "Đường số 18", "Đường số 54", "Nguyễn Ngọc Cung",
    "Bà Ký", "Đường số 19", "Đường số 6", "Nguyễn Phạm Tuân",
    "Bà Lài", "Đường số 2", "Đường số 64", "Nguyễn Thị Nhỏ",
    "Bãi Sậy", "Đường số 20", "Đường số 7", "Nguyễn Văn Luông",
    "Bến Lò Gốm", "Đường số 22", "Đường số 74", "Nguyễn Xuân Phụng",
    "Bến Phú Lâm", "Đường số 23", "Đường Số 76", "Phạm Đình Hổ",
    "Bình Phú", "Đường số 24", "Đường số 8", "Phạm Phú Thứ",
    "Bình Tây", "Đường số 26", "Đường số 9", "Phạm Văn Chí",
    "Bình Tiên", "Đường số 28", "Gia Phú", "Phan Anh",
    "Bửu Đình", "Đường Số 28A", "Hậu Giang", "Phan Văn Khỏe",
    "Cao Văn Lầu", "Đường số 29", "Hoàng Lê Kha", "Phùng Hưng",
    "Chánh Hưng", "Đường số 3", "Hồng Bàng", "Song Hành",
    "Chợ Lớn", "Đường số 30", "Hùng Vương", "Tân Hóa",
    "Chu Văn An", "Đường số 32", "Kinh Dương Vương", "Tân Hòa Đông",
    "2 Cư xá Phú Lâm A", "Đường số 33", "Lê Quang Sung", "Tháp Mười",
    "Cư xá Phú Lâm B", "Đường số 34", "Lê Tấn Kế", "Tiền Chế",
    "Cư xá Phú Lâm D", "Đường số 36", "Lê Trực", "Trần Bình",
    "Đặng Nguyên Cẩn", "Đường số 38", "Lê Tuấn Mậu", "Trần Trung Lập",
    "Đường 35C", "Đường số 4", "Lò Gốm", "Trần Văn Kiểu",
    "Đường số 1", "Đường số 40", "Lý Chiêu Hoàng", "Trang Tử",
    "Đường số 10", "Đường số 42", "Mai Xuân Thưởng", "Văn Thân",
    "Đường Số 10 Cx Rađa", "Đường số 44", "Minh Phụng", "Văn Thánh",
    "Đường số 11", "Đường số 47", "Ngô Nhân Tịnh", "Vành Đai",
    "Đường số 12", "Đường số 49", "Nguyễn Đình Chi", "Võ Văn Kiệt",
    "Đường số 14", "Đường số 5"
]
streets_district7 = [
    "Bắc Nam", "Đường Số 1H", "Đường số 66", "Nguyễn Khắc Viện",
    "Bế Văn Cấm", "Đường số 2", "Đường số 67", "2 Nguyễn Lương Bằng",
    "Bến Nghé", "Đường số 20", "Đường số 69", "Nguyễn Phan Chánh",
    "Bertrand Russell", "Đường số 21", "Đường số 6E", "Nguyễn Thị Thập",
    "Bờ Tây", "Đường số 22", "Đường số 7", "Nguyễn Tri Phương",
    "Bùi Bằng Đoàn", "Đường số 23", "Đường số 71", "2 Nguyễn Văn Cừ",
    "Bùi Văn Ba", "Đường số 25", "Đường Số 75", "Nguyễn Văn Linh",
    "Cao Triều Phát", "Đường số 25A", "Đường số 77", "Nguyễn Văn Quỳ",
    "Cầu Tân Thuận 2", "2 Đường số 27", "Đường số 79", "Nguyễn Văn Tiết",
    "Chuyên Dùng", "Đường số 28", "Đường số 8", "nội bộ khu Nam Phú",
    "Đặng Đại Độ", "Đường số 3", "Đường số 81", "Ô Đốc Tuyết",
    "Đặng Đức Thuật", "Đường số 30", "Đường số 85", "Phạm Hữu Lầu",
    "Đào Sư Tích", "Đường số 31", "Đường số 9", "Phạm Thái Bường",
    "Đào Trí", "Đường số 32", "Đường U", "Phạm Thiều",
    "Đào Trí Nối dài", "Đường số 33", "Gò Ô Môi", "Phạm Văn Nghị",
    "Đô Đốc Tuyết", "Đường số 34", "Hà Huy Tập", "Phạm Văn Nghị - Bắc",
    "Đường 10 (Tây)", "Đường số 35", "2 Hoàng Quốc Việt", "Phạm Viết Chánh",
    "Đường 4C", "Đường số 36", "Hoàng Văn Thái", "Phan Huy Thực",
    "Đường C", "Đường số 37", "Hưng Long", "Phan Khiêm Ích",
    "Đường D", "Đường số 38", "Huỳnh Tấn Phát", "Phan Văn Chương",
    "Đường D23", "2 Đường số 39", "Khu Mỹ Kim", "Phú Thuận",
    "Đường D4", "Đường số 3A", "Lâm văn Bền", "Rạch Dơi",
    "Đường D5B", "Đường số 4", "Lê Thánh Tôn", "Sáng Tạo",
    "Đường G", "Đường số 40", "Lê Văn Lương", "Tạ Quang Bửu",
    "Đường N", "Đường số 41", "Lê Văn Thiêm", "Tân An Huy",
    "Đường O", "Đường số 42", "Luther King", "Tân Mỹ",
    "Đường P", "2 Đường số 43", "Lưu Trọng Lư", "Tân Phú",
    "Đường số 1", "Đường số 45", "Lý Long Tường", "Tân Quy Đông",
    "2 Đường số 10", "Đường số 47", "Lý Phục Man", "Tân Thuận",
    "Đường số 11", "Đường số 49", "Mai Văn Vĩnh", "Tân Thuận Tây",
    "Đường số 11N", "Đường số 4F", "Morison", "Tân Trào",
    "Đường số 12", "Đường số 5", "Mỹ Thái", "Tiểu Bắc",
    "Đường số 12B", "Đường số 51", "Mỹ Viên", "Tiểu Đông",
    "Đường số 13", "Đường số 52", "Nam Quang 1", "Tiểu Nam",
    "2 Đường số 14", "Đường số 53", "Nam Thông 1", "Trần Trọng Cung",
    "Đường số 14A", "Đường số 5B", "Nam Thông 3", "Trần Văn Khánh",
    "Đường số 15", "Đường số 5K", "Nguyễn Bính", "Trần Văn Trà",
    "Đường số 15B", "2 Đường số 6", "Nguyễn Cao", "Trần Văn Trà",
    "Đường số 16", "Đường số 60", "Nguyễn Cao Nam", "Trần Xuân Soạn",
    "Đường số 17", "Đường số 61", "Nguyễn Đổng Chi", "Ưng Long Nam",
    "Đường số 18", "Đường số 62", "Nguyễn Đức Cảnh", "Xa lộ Bắc Nam",
    "Đường số 19", "Đường số 63", "Nguyễn Hữu Thọ"
]
streets_district8 = [
    "An Dương Vương", "Đường 233 Ba Tơ", "Đường Số 332", "Nguyễn Sĩ Cố",
    "An Tài", "Đường 267B Ba Tơ", "Đường số 4", "Nguyễn Thành Phương",
    "Âu Dương Lân", "Đường 270 Cao Lỗ", "Đường số 41", "Nguyễn Thị Tần",
    "Ba Đình", "Đường 284 Cao Lỗ", "Đường số 44", "Nguyễn Thị Thập",
    "Ba Tơ", "Đường 3052 Phạm Thế Hiển", "Đường số 5", "Nguyễn Tri Phương",
    "Bến Bình Đông", "Đường 3052A Phạm Thế Hiển", "Đường số 7", "Nguyễn Văn Cừ",
    "Bến Cần Giuộc", "Đường 320 Bông Sao", "Đường số 8", "Nguyễn Văn Của",
    "Bến Mễ Cốc", "Đường 320A Bông Sao", "Đường số 9", "Nguyễn Văn Linh",
    "Bến Phú Định", "Đường 643 Tạ Quang Bửu", "Hồ Học Lãm", "Nối Phạm Thế Hiển-BaTơ",
    "Bến Ụ Cây", "Đường 715 Tạ Quang Bửu", "Hoài Thanh", "Phạm Hùng",
    "Bến Xóm Củi", "Đường 817A", "Hoàng Đạo Thúy", "Phạm Thế Hiển",
    "Bình Đăng", "Đường 84 Cao Lỗ", "Hoàng Minh Đạo", "Phong Phú",
    "Bình Đông", "Đường 9 - Khu Thanh Nhựt", "Hoàng Sĩ Khải", "Phú Định",
    "Bình Đức", "Dương Bá Trạc", "Hưng Phú", "Phú Lợi",
    "Bình Hưng", "Đường D 2", "Huỳnh Thị Phụng", "Quốc Lộ 50",
    "Bông Sao", "Đường số 1", "Lê Quang Kim", "Rạch Cát",
    "Bùi Huy Bích", "Đường số 10", "Lê Thành Phương", "Rạch Cùng",
    "Bùi Minh Trực", "Đường số 1011", "Liên Tỉnh 5", "Rạch Lồng Đèn",
    "Cần Giuộc", "Đường số 102 Cao Lỗ", "Lương Ngọc Quyến", "Tạ Quang Bửu",
    "Cao Lỗ", "Đường số 1107", "Lương Văn Can", "Trần Nguyên Hãn",
    "Cao Xuân Dục", "Đường số 111", "Lưu Hữu Phước", "Trần Văn Thành",
    "Cây Sung", "Đường số 12", "Lưu Quý Kỳ", "Trịnh Quang Nghị",
    "Chánh Hưng", "Đường số 13", "Lý Chiêu Hoàng", "Trương Đình Hội",
    "Dạ Nam", "Đường số 14", "Lý Đạo Thành", "Tùng Thiện Vương",
    "Dã Tượng", "Đường số 15", "Mạc Vân", "Tuy Lý Vương",
    "Đặng Chất", "Đường số 16", "Mai Am", "Ưu Long",
    "Đào Cam Mộc", "Đường số 16 ND", "Mai Hắc Đế", "Vạn Kiếp",
    "Đình An Tài", "Đường số 2", "Mễ Cốc", "Văn Thân",
    "Đinh Hòa", "Đường số 22", "Ngô Sỹ Liên", "Vĩnh Nam",
    "Đồng Diều", "Đường số 23", "Nguyễn Chế Nghĩa", "Võ Trứ",
    "Đông Hồ", "Đường số 29", "Nguyễn Duy", "2 Võ Văn Kiệt",
    "Đường 152 Cao Lỗ", "Đường số 3", "Nguyễn Duy Dương", "Xóm Củi",
    "Đường 198 Cao Lỗ", "Đường Số 318", "Nguyễn Ngọc Cung",
    "Đường 204 Cao Lỗ", "Đường Số 320", "Nguyễn Nhược Thị",
    "Đường 232 Cao Lỗ", "Đường số 33", "Nguyễn Quyền"
]
streets_district9 = [
    "An Thiên Lý", "Đường số 168", "Đường số 5", "Long Thuận",
    "Bách Khoa", "Đường số 17", "Đường số 5A", "Mạc Hiển Tích",
    "Bùi Quốc Khái", "Đường số 176", "Đường số 6", "Man Thiện",
    "Bùi Xương Trạch", "Đường số 179", "Đường số 61", "Nam Cao",
    "Bưng Ông Thoàn", "Đường số 18", "Đường số 623", "Nam Hòa",
    "Bưng Sáu Xã", "Đường số 182", "Đường số 671", "Nam Long",
    "Cầu Đình", "Đường số 185", "Đường số 68", "Ngô Quyền",
    "Cầu xây", "Đường số 18A", "Đường số 6A", "Nguyễn Công Trứ",
    "Cầu Xây 1", "Đường số 18B", "Đường số 6B", "Nguyễn Duy Trinh",
    "Cầu xây 2", "Đường số 197", "Đường số 6C", "Nguyễn Thái Học",
    "Châu Phúc cẩm", "Đường số 2", "Đường số 6D", "Nguyễn Thị Định",
    "Cô Bắc", "Đường số 20", "Đường số 7", "Nguyễn Văn Tăng",
    "Đại Lộ 2", "Đường số 207", "Đường số 74", "Nguyễn Văn Thạnh",
    "Đại lộ 3", "Đường số 21", "Đường số 79", "Nguyễn Xiển",
    "Dân Chủ", "Đường số 210", "Đường số 8", "Nhà Thiếu Nhi",
    "Đinh Củng Viên", "Đường số 212", "Đường số 85", "Phan Chu Trinh",
    "Đình Phong Phú", "Đường số 215", "Đường số 882", "Phan Đạt Đức",
    "Đỗ Thế Diên", "Đường số 22", "Đường số 885", "Phan Đình Phùng",
    "Đỗ Xuân Hợp", "Đường số 228", "Đường số 898", "Phước Hữu",
    "Đường 816", "Đường số 23", "Đường số 9", "Phước Thiện",
    "Đường D1", "Đường số 236", "Đường số 904", "Quang Trung",
    "Đường D2", "Đường số 24", "Đường số 990", "Quốc Lộ 50",
    "Đường D3", "Đường số 245", "Gò Cát", "Tam Đa",
    "Đường D400", "Đường số 25", "Gò Nổi", "Tản Đà",
    "Dương Đình Hội", "Đường số 265", "Hà Phú Hữu", "Tân Hòa II",
    "Đường N7", "Đường số 27", "Hai Bà Trưng", "Tân Lập I",
    "Đường số 1", "Đường số 275", "Hàng Tre", "Tân Lập II",
    "Đường số 10", "Đường số 29", "Hồ Bá Phấn", "Tăng Nhơn Phú",
    "Đường số 100", "Đường số 297", "Hoàng Hữu Nam", "Tây Hòa",
    "Đường số 102", "Đường số 3", "Hồng Sến", "Thủy Lợi",
    "Đường số 106", "Đường số 30", "Huỳnh Thúc Kháng", "Tổ 1",
    "Đường số 109", "Đường số 311", "Ích Thạnh", "Trần Hưng Đạo",
    "Đường số 11", "Đường số 33", "Khổng Tử", "Trần Quốc Toản",
    "Đường số 12", "Đường số 339", "Lã Xuân Oai", "Trần Trọng Khiêm",
    "Đường số 120", "Đường số 359", "Lạc Thiện", "Trịnh Hoài Đức",
    "Đường số 12E", "Đường số 379", "Làng Tăng Phú", "Trương Hanh",
    "Đường số 13", "Đường số 385", "Lê Lợi", "Trường Lưu",
    "Đường số 138", "Đường số 4", "Lê Văn Thịnh", "Trương Văn Hải",
    "Đường số 144", "Đường số 400", "Lê Văn Việt", "Trương Văn Thành",
    "Đường số 147", "Đường Số 449", "Liên Phường", "Tú Xương",
    "Đường số 15", "Đường số 475", "Lò Lu", "Võ Tiên Sư",
    "Đường số 154", "Đường số 48", "Long Phước",
    "Đường số 16", "Đường số 49", "Long Sơn",
    "Đường số 160", "Đường số 494", "Long Thành"
]
streets_district10 = [
    "Bà Hạt", "Hồ Bá Kiện", "Lý Thái Tổ", "Tam Đảo",
    "Ba Vì", "Hồ Thị Kỷ", "Lý Thường Kiệt", "Tân Phước",
    "Bắc Hải", "Hòa Bình", "Ngô Gia Tự", "Thành Thái",
    "Bạch Đằng", "Hòa Hảo", "Ngô Quyền", "Thất Sơn",
    "Bạch Mã", "Hòa Hưng", "Nguyễn Chí Thanh", "Thiên Phước",
    "Bàn Cờ", "Hoàng Dư Khương", "Nguyễn Duy Dương", "Tô Hiến Thành",
    "Bửu Long", "Hoàng Văn Thụ", "Nguyễn Giản Thanh", "Trần Bình Trọng",
    "Cách Mạng Tháng 8", "Hồng Bàng", "Nguyễn Kim", "Trần Hưng Đạo",
    "Cao Thắng", "Hồng Lĩnh", "Nguyễn Lâm", "Trần Minh Quyền",
    "Châu Thới", "Hưng Long", "Nguyễn Ngọc Lộc", "Trần Nhân Tôn",
    "Cửu Long", "Hùng Vương", "Nguyễn Thị Định", "Trần Quốc Dung",
    "Đào Duy Từ", "Hương Giang", "Nguyễn Thượng Hiền", "Trần Quý",
    "Đào Nguyên Phổ", "Kênh Nhiêu Lộc", "Nguyễn Tiểu La", "Trần Thiện Chánh",
    "Đất Thánh", "Kỳ Hòa", "Nguyễn Tri Phương", "Trần Văn Đang",
    "Điện Biên Phủ", "Lãnh Binh Thăng", "Nguyễn Trung Trực", "Trường Chinh",
    "Đồng Nai", "Lê Đại Hành", "Nguyễn Văn Lượng", "Trường Sơn",
    "Đường 3 Tháng 2", "Lê Hồng Phong", "Nhật Tảo", "Vĩnh Viễn",
    "Hầu Thới", "Lữ Gia", "Sư Vạn Hạnh"
]
streets_district11 = [
    "Âu Cơ", "Đường số 5A", "Lạc Long Quân", "Phú Thọ",
    "Bình Thới", "Đường số 6", "Lãnh Binh Thăng", "Quân Sự",
    "Công Chúa Ngọc Hân", "Đường số 7", "Lê Đại Hành", "Tạ Uyên",
    "Đặng Minh Khiêm", "Đường số 702", "Lê Thị Bạch Cát", "Tản Đà",
    "Đào Nguyên Phổ", "Đường số 762", "Lê Tung", "Tân Hóa",
    "Đỗ Ngọc Thạnh", "Đường số 7A", "Lò Siêu", "Tân Khai",
    "Đội Cung", "Đường số 8", "Lữ Gia", "Tân Phước",
    "Đường 3 Tháng 2", "Đường số 9", "Lý Nam Đế", "Tân Thành",
    "Dương Đình Nghệ", "Dương Tử Giang", "Lý Thường Kiệt", "Thái Phiên",
    "Đường số 100", "EverRich", "Mai Xuân Thưởng", "Thiên Phước",
    "Đường số 13", "Hà Tôn Quyền", "Minh Phụng", "Thuận Kiều",
    "Đường số 16", "Hàn Hải Nguyên", "Ngô Quyền", "Tôn Thất Hiệp",
    "Đường số 2", "Hòa Bình", "Nguyễn Bá Học", "Tổng Lung",
    "Đường số 22", "Hòa Hảo", "Nguyễn Chí Thanh", "Tống Văn Trân",
    "Đường số 281", "Hoàng Đức Tương", "Nguyễn Thị Nhỏ", "Trần Quý",
    "Đường số 3", "Hoàng Xuân Nhị", "Nguyễn Văn Phú", "Trịnh Đình Trọng",
    "Đường số 34", "Hồng Bàng", "Nhật Tảo", "Tuệ Tĩnh",
    "Đường số 3A", "Hùng Vương", "Ông Ích Khiêm", "Vĩnh Viễn",
    "Đường số 4", "Huyện Toại", "Phan Xích Long", "Võ Văn Tần",
    "Đường số 5", "Khuông Việt", "Phó Cơ Điều", "Xóm Đất"
]
streets_district12 = [
    "An Lộc", "Đường HT 48", "Nguyễn Văn Quá", "Thạnh Lộc 29",
    "An Phú Đông", "Đường HT 49", "Phan Văn Hớn", "Thạnh Lộc 30",
    "An Phú Đông 1", "Đường HT02", "Quán Tre", "Thạnh Lộc 31",
    "An Phú Đông 25", "Đường số 13", "Quang Trung", "Thạnh Lộc 37",
    "An Phú Đông 27", "Đường số 17", "Quốc Lộ 1A", "Thạnh Lộc 41",
    "An Phú Đông 3", "Đường số 30", "Quốc Lộ 22", "Thạnh Lộc 50",
    "An Phú Đông 9", "Đường số 42", "Song Hành", "Thạnh Lộc 54",
    "Bùi Công Trừng", "Đường số 5", "Song Hành Quốc Lộ 22", "Thạnh Xuân 13",
    "Bùi Văn Ngữ", "Đường số 7", "Tân Chánh Hiệp", "Thạnh Xuân 14",
    "Cao tốc Xuyên Á", "Đường T12", "Tân Chánh Hiệp 03", "Thạnh Xuân 16",
    "Cầu Lò Heo", "Đường T15", "Tân Chánh Hiệp 05", "Thạnh Xuân 22",
    "Đình Giao Khẩu", "Đường TX 18", "Tân Chánh Hiệp 07", "Thạnh Xuân 25",
    "Đỗ Quyên", "Đường TX 21", "Tân Chánh Hiệp 08", "Thạnh Xuân 38",
    "Đông Bắc", "Đường TX 22", "Tân Chánh Hiệp 10", "Thạnh Xuân 52",
    "Đông Hưng Thuận", "Đường TX 24", "Tân Chánh Hiệp 13", "Thới An",
    "Đông Hưng Thuận 02", "Đường TX 25", "Tân Chánh Hiệp 16", "Thới An 09",
    "Đông Hưng Thuận 03", "Đường TX 31", "Tân Chánh Hiệp 17", "Thới An 10",
    "Đông Hưng Thuận 05", "Đường TX 43", "Tân Chánh Hiệp 18", "Thới An 11",
    "Đông Hưng Thuận 10", "Đường TX 48", "Tân Chánh Hiệp 21", "Thới An 12",
    "Đông Hưng Thuận 10B", "Giang Cự Vọng", "Tân Chánh Hiệp 24", "Thới An 13",
    "Đông Hưng Thuận 11", "Giáng Hương", "Tân Chánh Hiệp 25", "Thới An 15",
    "Đông Hưng Thuận 12", "Hà Chương", "Tân Chánh Hiệp 33", "Thới An 16",
    "Đông Hưng Thuận 14", "Hà Đặc", "Tân Chánh Hiệp 34", "Thới An 18",
    "Đông Hưng Thuận 17", "Hà Huy Giáp", "Tân Chánh Hiệp 35", "Thới An 19",
    "Đông Hưng Thuận 2", "Hiệp Thành", "Tân Chánh Hiệp 36", "Thới An 20",
    "Đông Hưng Thuận 21", "Hiệp Thành 05", "Tân Thới Hiệp", "Thới An 21",
    "Đông Hưng Thuận 3", "Hiệp Thành 06", "Tân Thới Hiệp 1", "Thới An 32",
    "Đông Hưng Thuận 30", "Hiệp Thành 10", "Tân Thới Hiệp 10", "Thới An 35",
    "Đông Hưng Thuận 32", "Hiệp Thành 12", "Tân Thới Hiệp 13", "Thới An 4",
    "Đông Hưng Thuận 42", "Hiệp Thành 13", "Tân Thới Hiệp 15", "Thới An 5",
    "Đông Hưng Thuận 45", "Hiệp Thành 17", "Tân Thới Hiệp 17", "Thới An 6",
    "Đông Hưng Thuận 5", "Hiệp Thành 18", "Tân Thới Hiệp 2", "Thới Tam Thôn 12",
    "Đông Hưng Thuận 6", "Hiệp Thành 19", "Tân Thới Hiệp 20", "Tỉnh Lộ 14",
    "Đông Hưng Thuận 9", "Hiệp Thành 22", "Tân Thới Hiệp 21", "Tỉnh Lộ 15",
    "Đường HT 5", "Hiệp Thành 23", "Tân Thới Hiệp 22", "Tỉnh lộ 28",
    "Đường 02", "Hiệp Thành 26", "Tân Thới Hiệp 7", "Tỉnh Lộ 29",
    "Đường DD11", "Hiệp Thành 27", "Tân Thới Nhất", "Tỉnh Lộ 31",
    "Đường DD12", "Hiệp Thành 31", "Tân Thới Nhất 09", "TL 16",
    "Đường DD4", "Hiệp Thành 33", "Tân Thới Nhất 1", "TL 27",
    "Đường DD5", "Hiệp Thành 37", "Tân Thới Nhất 11", "TMT 09",
    "Đường ĐHT 10B", "Hiệp Thành 39", "Tân Thới Nhất 12", "Tô Ký",
    "Đường ĐHT 45", "Hiệp Thành 42", "Tân Thới Nhất 13", "Tô Ngọc Vân",
    "Đường DN 10", "Hiệp Thành 44", "Tân Thới Nhất 17", "Trung Mỹ Tây",
    "Đường ĐT 1-2", "Hiệp Thành 5", "Tân Thới Nhất 2", "Trung Mỹ Tây 05",
    "Đường HT 13", "Hiệp Thành 6", "Tân Thới Nhất 21", "Trung Mỹ Tây 08",
    "Đường HT 17", "Hương Lộ 80B", "Tân Thới Nhất 4", "Trung Mỹ Tây 1",
    "Đường HT 18", "Huỳnh Thị Hai", "Tân Thới Nhất 5", "Trung Mỹ Tây 12",
    "Đường HT 22", "Lâm Thị Hố", "Tân Thới Nhất 6", "Trung Mỹ Tây 13",
    "Đường HT 23", "Lê Đức Thọ", "Tân Thới Nhất 8", "Trung Mỹ Tây 18A",
    "Đường HT 26", "Lê Thị Riêng", "Tân Thới Nhất 8", "Trung Mỹ Tây 2A",
    "Đường HT 27", "Lê Văn Khương", "Tân Thới Nhất 8", "Trung Mỹ Tây 5",
    "Đường HT 31", "Liên Phường", "TCH 22", "Trung Mỹ Tây 6A",
    "Đường HT 32", "Nguyễn An Ninh", "Thạnh Lộc 14", "Trường Chinh",
    "Đường HT 35", "Nguyễn Ảnh Thủ", "Thạnh Lộc 15", "Vườn Lài"
]
streets_district_binhthanh = [
    "Bắc Bình", "Đường số 5", "Nguyễn Công Trứ", "Phan Văn Hân",
    "Bạch Đằng", "Đường số 6", "Nguyễn Cửu Vân", "Phan Văn Trị",
    "Bình Lợi", "Đường số 8", "Nguyễn Duy", "Phan Xích Long",
    "Bình Quới", "Đường số 82", "Nguyên Hồng", "Phó Đức Chính",
    "Bùi Đình Túy", "Đường Trục", "Nguyễn Hữu Cảnh", "Phú Mỹ",
    "Bùi Hữu Nghĩa", "Hồ Xuân Hương", "Nguyễn Huy Lượng", "Quốc Lộ 13",
    "Chu Văn An", "Hoàng Hoa Thám", "Nguyễn Huy Tưởng", "Tầm Vu",
    "Công Trường Hòa Bình", "Hồng Bàng", "Nguyễn Khuyến", "Tăng Bạt Hổ",
    "Công Trường Tự Do", "Huỳnh Đình Hai", "Nguyễn Kiệm", "Thanh Đa",
    "Cửu Long", "Huỳnh Khương An", "Nguyễn Lâm", "Thiên Hộ Dương",
    "Điện Biên Phủ", "Huỳnh Mẫn Đạt", "Nguyễn Ngọc Phương", "Trần Bình Trọng",
    "Diên Hồng", "Huỳnh Tá Bang", "Nguyễn Thái Học", "Trần Kế Xương",
    "Đinh Bộ Lĩnh", "Huỳnh Thúc Kháng", "Nguyễn Thái Sơn", "Trần Quốc Tuấn",
    "Đinh Tiên Hoàng", "Huỳnh Tịnh Của", "Nguyễn Thị Tú", "Trần Quý Cáp",
    "Đống Đa", "Lái Thiêu", "Nguyễn Thiện Thuật", "Trần Văn Kỷ",
    "Đường D1", "Lam Sơn", "Nguyễn Thượng Hiền", "Trịnh Hoài Đức",
    "Đường D2", "Lê Hoàng Phái", "Nguyễn Trọng Tuyển", "Trục 30m",
    "Đường D3", "Lê Lợi", "Nguyễn Trung Trực", "Trường Sa",
    "Đường D4", "Lê Quang Định", "Nguyễn Văn Đậu", "Ung Văn Khiêm",
    "Đường D5", "Lê Trực", "Nguyễn Văn Lạc", "Vạn Kiếp",
    "Đường số 1", "Lê Tự Tài", "Nguyễn Xí", "Văn Thánh Bắc",
    "Đường số 10", "Lương Ngọc Quyến", "Nguyễn Xuân Ôn", "Võ Duy Ninh",
    "Đường số 12AB", "Mai Xuân Thưởng", "Nơ Trang Long", "Võ Thành Trang",
    "Đường số 14", "Mê Linh", "Phạm Văn Đồng",
    "Đường số 16", "Miếu Nổi", "Phạm Văn Hải", "Vũ Huy Tấn",
    "Đường số 18", "Ngô Đức Kế", "Phạm Viết Chánh", "Vũ Ngọc Phan",
    "Đường số 2", "Ngô Nhân Tịnh", "Phan Bội Châu", "Vũ Tùng",
    "Đường số 3", "Ngô Tất Tố", "Phan Chu Trinh", "Xô Viết Nghệ Tĩnh",
    "Đường số 304", "Nguyễn An Ninh", "Phan Đăng Lưu",
    "Đường số 4", "Nguyễn Bỉnh Khiêm", "Phan Đình Phùng",
    "Đường số 48", "Nguyễn Công Hoan", "Phan Huy Ôn"
]
streets_district_tanbinh = [
    "Ấp Bắc", "Đường C18", "Lương Thế Vinh", "Sông Đáy",
    "Âu Cơ", "Đường C2", "Lưu Nhân Chú", "Sông Nhuệ",
    "Ba Gia", "Đường C22", "Lý Thường Kiệt", "Sông Thao",
    "Ba Vân", "Đường C27", "Mai Lão Bạng", "Sông Thương",
    "Ba Vì", "Đường C3", "Năm Châu", "Tân Canh",
    "Bắc Hải", "Đường D10", "Nghĩa Hòa", "Tân Châu",
    "Bạch Đằng", "Đường D50", "Nghĩa Hưng", "Tân Hải",
    "Bạch Đằng 1", "Đường D51", "Nghĩa Phát", "Tân Khai",
    "Bạch Đằng 2", "Đường D52", "Ngô Bệ", "Tân Kỳ Tân Quý",
    "Bạch Mã", "Đường số 1", "Ngô Thị Thu Minh", "Tân Lập",
    "Bành Văn Trân", "Đường số 175", "Ngự Bình", "Tân Phước",
    "Bàu Bàng", "Đường số 2", "Nguyễn Bá Tòng", "Tân Sơn",
    "Bàu Cát", "Đường số 3", "Nguyễn Bá Tuyển", "Tân Sơn Hòa",
    "Bàu Cát 1", "Đường số 4", "Nguyễn Bặc", "Tân Sơn Nhì",
    "Bàu Cát 2", "Đường số 5", "Nguyễn Cảnh Dị", "Tân Tạo",
    "Bàu Cát 3", "Đường số 6", "Nguyễn Chánh Sắt", "Tân Thọ",
    "Bàu Cát 4", "Đường số 7", "Nguyễn Đình Khơi", "Tân Tiến",
    "Bàu Cát 5", "Dương Văn Dương", "Nguyễn Đức Thuận", "Tân Trang",
    "Bàu Cát 6", "Dương Vân Nga", "Nguyễn Hiến Lê", "Tân Trụ",
    "Bàu Cát 7", "Duy Tân", "Nguyễn Hồng Đào", "Tản Viên",
    "Bàu Cát 8", "Giải Phóng", "Nguyễn Minh Hoàng", "Tân Xuân",
    "Bàu Cát 9", "Gò Cẩm Đệm", "Nguyễn Phúc Chu", "Thái Thị Nhạn",
    "Bàu Cát Đôi", "Gò Dầu", "Nguyễn Quang Bích", "Thân Nhân Trung",
    "Bảy Hiền", "Hà Bá Tường", "Nguyễn Sơn", "Thăng Long",
    "Bế Văn Đàn", "Hát Giang", "Nguyễn Sỹ Sách", "Thành Mỹ",
    "Bến Cát", "Hậu Giang", "Nguyễn Thái Bình", "Thép Mới",
    "Bình Giã", "Hiệp Nhất", "Nguyễn Thanh Tuyền", "Thích Minh Nguyệt",
    "Bùi Thế Mỹ", "Hồ Đắc Di", "Nguyễn Thế Lộc", "Thiên Phước",
    "Bùi Thị Xuân", "Hòa Bình", "Nguyễn Thị Nhỏ", "Thủ Khoa Huân",
    "Bùi Tư Toàn", "Hòa Hiệp", "Nguyễn Trọng Lội", "Tiền Giang",
    "Ca Văn Thỉnh", "Hoàng Bật Đạt", "Nguyễn Trọng Tuyển", "Tống Văn Hên",
    "Cách Mạng Tháng 8", "Hoàng Hoa Thám", "Nguyễn Tử Nha", "Trà Khúc",
    "Cầu Cống Lở", "Hoàng Kế Viêm", "Nguyễn Văn Mại", "Trần Đình Trọng",
    "Chấn Hưng", "Hoàng Sa", "Nguyễn Văn Trỗi", "Trần Mai Ninh",
    "Châu Vĩnh Tế", "Hoàng Văn Thụ", "Nguyễn Văn Vĩ", "Trần Quốc Hoàn",
    "Chí Công", "Hoàng Việt", "Nguyễn Văn Vĩnh", "Trần Thái Tông",
    "Chí Linh", "Hồng Hà", "Nguyễn Xuân Khoát", "Trần Thánh Tông",
    "Chử Đồng Tử", "Hồng Lạc", "Nhất Chi Mai", "Trần Triệu Luật",
    "Cộng Hòa", "Hưng Hóa", "Ni Sư Huỳnh Liên", "Trần Văn Đang",
    "Cống Lở", "Hương lộ 2", "Núi Thành", "Trần Văn Danh",
    "Cù Chính Lan", "Huỳnh Lan Khanh", "Phạm Cự Lượng", "Trần Văn Dư",
    "Cửu Long", "Huỳnh Tịnh Của", "Phạm Hồng Thái", "Trần Văn Hoàng",
    "Đại Nghĩa", "Huỳnh Văn Nghệ", "Phạm Phú Thứ", "Trần Văn Quang",
    "Dân Trí", "Kênh Nhiêu Lộc", "Phạm Văn Bạch", "Trịnh Đình Thảo",
    "Đặng Lộ", "Khai Quang", "Phạm văn hai", "Trung Lang",
    "Đặng Minh Trứ", "Khai Trí", "Phan Anh", "Trường Chinh",
    "Đất Thánh", "Khuông Việt", "Phan Bá Phiến", "Trương Công Định",
    "Đinh Điền", "Lạc Long Quân", "Phan Đình Giót", "Trương Hoàng Thanh",
    "Đồ Sơn", "Lam Sơn", "Phan Huy Ích", "Trường Sa",
    "Dọc Bờ Kênh Nhiêu Lộc", "Lê Bình", "Phan Sào Nam", "Trường Sơn",
    "Đống Đa", "Lê Duy Nhuận", "Phan Thúc Duyện", "Tự Cường",
    "Đồng Đen", "Lê Lai", "Phan Văn Lâu", "Tứ Hải",
    "Đông Hồ", "Lê Lợi", "Phan Văn Sửu", "Tự Lập",
    "Đồng Khởi", "Lê Minh Xuân", "Phổ Quang", "Út Tịch",
    "Đồng Nai", "Lê Ngân", "Phú Hoà", "Văn Chung",
    "Đông Sơn", "Lê Tấn Quốc", "Phú Lộc", "Vân Côi",
    "Đồng Xoài", "Lê Trọng Tấn", "Quách Văn Tuấn", "Võ Thành Trang",
    "Đường 27 Tháng 3", "Lê Trung Nghĩa", "Quảng Hiền", "Vườn Lan",
    "Đường A4", "Lê Văn Huân", "Sầm Sơn", "Xuân Diệu",
    "Đường B1", "Lê Văn Sỹ", "Sao Mai", "Xuân Hồng",
    "Đường B6", "Lộc Hưng"]
streets_district_tanphu = [
    "Âu Cơ", "Đường CN13", "Khuông Việt", "Nguyễn Văn Ngọc",
    "Âu Dương Lân", "Đường CN6", "Lê Cảnh Tuân", "Nguyễn Văn Săng",
    "Bác Ái", "Đường D10", "Lê Cao Lãng", "Nguyễn Văn Tố",
    "Bình Long", "Đường D11", "Lê Đại", "Nguyễn Văn Vịnh",
    "Bờ Bao Tân Thắng", "Đường D12", "Lê Đình Thám", "Nguyễn Xuân Khoát",
    "Bùi Cẩm Hổ", "Đường D13", "Lê Đình Thụ", "Phạm Ngọc",
    "Bùi Thế Mỹ", "Đường D14A", "Lê Khôi", "Phạm Quý Thích",
    "Bùi Xuân Phái", "Đường D14B", "Lê Lâm", "Phạm Vấn",
    "Cách Mạng", "Đường D15", "Lê Lăng", "Phạm Văn Xảo",
    "Cách Mạng Tháng 8", "Đường D16", "Lê Liễu", "Phan Anh",
    "Cao thế", "Đường D9", "Lê Lộ", "Phan Chu Trinh",
    "Cao Văn ngọc", "Đường DC1", "Lê Lư", "Phan Đình Phùng",
    "Cầu Xéo", "Đường DC11", "Lê Ngã", "Phan Văn Năm",
    "Cây Keo", "Đường DC13", "Lê Niệm", "Phố Chợ",
    "Chân Lý", "Đường DC3", "Lê Quang Chiểu", "Phú Thọ Hòa",
    "Chế Lan Viên", "Đường DC4", "Lê Quốc Trinh", "Phùng Chí Kiên",
    "Chu Thiên", "Đường DC5", "Lê Sao", "Quách Đình Bảo",
    "Chu Văn An", "Đường DC7", "Lê Sát", "Quách Hữu Nghiêm",
    "Cộng Hòa 3", "Đường DC9", "Lê Thận", "Quách Vũ",
    "Đàm Thận Huy", "Dương Đức Hiền", "Lê Thiệt", "Sơn Kỳ",
    "Dân Chủ", "Đường Kênh 19/5", "Lê Thúc Hoạch", "Tân Hương",
    "Dân Tộc", "Dương Khuê", "Lê Trọng Tấn", "Tân Kỳ Tân Quý",
    "Điện Cao Thế", "Đường M5", "Lê Trúc", "Tân Quý",
    "Diệp Minh Châu", "Đường S1", "Lê Trung Đình", "Tân Sơn Nhì",
    "Đinh Liệt", "Đường S11", "Lê Văn Phan", "Tân Thành",
    "Đỗ Bí", "Đường S3", "Lê Vĩnh Hòa", "Tây Sơn",
    "Đỗ Công Tường", "Đường S5", "Lương Đắc Bằng", "Tây Thạnh",
    "Đô Đốc Chấn", "Đường S7", "Lương Minh Nguyệt", "Thạch Lam",
    "Đô Đốc Lộc", "Đường S9", "Lương Thế Vinh", "Thẩm Mỹ",
    "Đô Đốc Long", "Đường số 1", "Lương Trúc Đàm", "Thành Công",
    "Đô Đốc Thủ", "Đường số 18", "Lưu Chí Hiếu", "Thoại Ngọc Hầu",
    "Đỗ Đức Dục", "Đường số 19", "Lũy Bán Bích", "Thống Nhất",
    "Đỗ Nhuận", "Đường số 2", "Lý Thái Tông", "tổ 46",
    "Đỗ Thị Tâm", "Đường số 27", "Lý Thánh Tông", "Tổ 48",
    "Đỗ Thừa Luông", "Đường T1", "Lý Tuệ", "Tô Hiệu",
    "Đỗ Thừa Tự", "Đường T4A", "Ngô Quyền", "Trần Đình Trọng",
    "Đoàn Giỏi", "Đường T4B", "Nguyễn Bá Tòng", "Trần Hưng Đạo",
    "Đoàn Hồng Phước", "Đường T5", "Nguyễn Chích", "Trần Quang Cơ",
    "Đoàn Kết", "Đường T6", "Nguyễn Cửu Đàm", "Trần Tấn",
    "Độc Lập", "Đường T8", "Nguyễn Cửu Phú", "Trần Thủ Độ",
    "Đường 30 Tháng 4", "Dương Thiệu Tước", "Nguyễn Đỗ Cung", "Trần Văn Cẩn",
    "Đường B", "Dương Văn Dương", "Nguyễn Dữ", "Trần Văn Giáp",
    "Đường B2", "Gò Dầu", "Nguyễn Hảo Vĩnh", "Trần Văn Ơn",
    "Đường B3", "Gò Xoài", "Nguyễn Hậu", "Trịnh Đình Thảo",
    "Đường C1", "Hàn Mạc Tử", "Nguyễn Hữu Dật", "Trịnh Đình Trọng",
    "Đường C4", "Hiền Vương", "Nguyễn Hữu Tiến", "Trịnh Lỗi",
    "Đường C4A", "Hồ Đắc Di", "Nguyễn Lộ Trạch", "Trường Chinh",
    "Đường C5", "Hồ Ngọc Cẩn", "Nguyễn Lý", "Trương Vân Lĩnh",
    "Đường C6", "Hoa Bằng", "Nguyễn Minh Châu", "Trương Vĩnh Ký",
    "Đường C6A", "Hòa Bình", "Nguyễn Mỹ Ca", "Tự Do",
    "Đường C7", "Hoàng Ngọc Phách", "Nguyễn Ngọc Nhựt", "Tự do 1",
    "Đường C8", "Hoàng Thiều Hoa", "Nguyễn Nhữ Lãm", "Tự Quyết",
    "Đường CC1", "Hoàng Văn Hòe", "Nguyễn Quang Diệu", "Văn Cao",
    "Đường CC2", "Hoàng Xuân Nhị", "Nguyễn Quý Anh", "Vạn Hạnh",
    "Đường CC3", "Hương lộ 3", "Nguyễn Sơn", "Võ Hoành",
    "Đường CC4", "Huỳnh Thiện Lộc", "Nguyễn Súy", "Võ Văn Dũng",
    "Đường CC5", "Huỳnh Văn Chính", "Nguyễn Thái Học", "Vũ Trọng Phụng",
    "Đường CN 11", "Huỳnh Văn Một", "Nguyễn Thế Truyện", "Vườn Lài",
    "Đường CN 13", "Ích Thiện", "Nguyễn Thiện Lâu", "Ỷ Lan",
    "Đường CN 6", "Kênh 19 Tháng 5", "Nguyễn Trường Tộ", "Yên Đỗ",
    "Đường CN1", "Kênh Nước Đen", "Nguyễn Uẩn Sang", "Nguyễn Văn Huyên",
]
streets_district_binhtan = [
    "An Dương Vương", "Đường số 19B", "Đường số 52A", "Liên Khu 5",
    "Ao Đôi", "Đường số 19E", "Đường số 52B", "3 Liên Khu 5-11-12",
    "Ao Sen", "Đường số 1A", "Đường số 53", "Liên khu 5-6",
    "Ấp Chiến Lược", "Đường số 1B", "Đường số 532", "Liên Khu 7-13",
    "Bà Hom", "Đường số 1C", "Đường số 53A", "Liên Khu 8-9",
    "Bến Lội", "Đường số 1D", "Đường số 53C", "Lộ Tẻ",
    "Bia Truyền Thống", "Đường số 2", "Đường số 53D", "Lô Tư",
    "Bình Hành", "Đường số 20", "Đường số 54", "Lý Chiêu Hoàng",
    "Bình Long", "Đường số 21", "Đường số 54A", "Lý Thánh Tông",
    "Bình Thành", "Đường số 21A", "Đường số 55", "Mã Lò",
    "Bình Trị Đông", "Đường Số 21D", "Đường số 55A", "Miếu Bình Đông",
    "Bờ sông", "Đường số 22", "Đường số 57", "Miếu Gò Xoài",
    "Bờ Tuyến", "Đường số 23", "Đường số 57A", "Nghi Xuân",
    "Bông Sen", "Đường số 24", "Đường số 57B", "Ngô Y Linh",
    "Bùi Dương Lịch", "Đường số 24A", "Đường số 57C", "Nguyễn Cửu Phú",
    "Bùi Hữu Diên", "Đường số 24B", "Đường số 59D", "Nguyễn Đình Kiên",
    "Bùi Tư Toàn", "2 Đường số 25", "Đường số 5A", "Nguyễn Hới",
    "Cao Tốc Trung Lương", "Đường số 25A", "2 Đường số 5B", "Nguyễn Hữu Cảnh",
    "Cầu Kinh", "Đường số 26", "Đường số 5C", "Nguyễn Quý Yêm",
    "Cây Cám", "Đường số 27", "2 Đường số 5D", "Nguyễn Sơn",
    "Chiến Lược", "Đường số 28", "Đường số 5E", "Nguyễn Thị Tú",
    "Cống Hộp", "Đường số 29", "Đường số 5F", "Nguyễn Thức Đường",
    "Đại lộ Đông Tây", "Đường số 2A", "2 Đường số 6", "Nguyễn Thức Tự",
    "Đất Mới", "Đường số 2B", "Đường số 6A", "Nguyễn Triệu Luật",
    "Đình Nghi Xuân", "Đường số 2C", "Đường số 7", "Nguyễn Trọng Chí",
    "Đình Tân Khai", "Đường số 2D", "Đường số 7A", "Nguyễn Trọng Trí",
    "Đỗ Bí", "Đường số 3", "Đường số 7B", "Nguyễn Văn Cừ",
    "Đỗ Năng Tế", "Đường số 30", "Đường số 8", "Phạm Bành",
    "Đoàn Phú Tứ", "Đường số 32", "Đường số 8B", "Phạm Đăng Giảng",
    "Đường 14E", "2 Đường số 33B", "Đường số 9", "Phan Anh",
    "Đường 26 Tháng 3", "Đường số 34", "Đường số 9A", "Phan Cát Tựu",
    "Đường A5", "Đường số 36", "Đường số 9B", "Phan Đình Thông",
    "Đường A6", "Đường số 38", "Đường Trung Tâm", "Phan Văn Năm",
    "Dương Bá Cung", "Đường số 39", "Dương Tự Quán", "Phùng Tá Chu",
    "Đường Đôi", "2 Đường số 3A", "Gò Xoài", "Quốc Lộ 1A",
    "Đường G1", "Đường số 3B", "Hồ Học Lãm", "Sông Suối",
    "Đường G7", "Đường số 3C", "Hồ Văn Long", "Sông Tắc",
    "Đường Kênh C", "Đường số 4", "Hoàng Hưng", "Tạ Mỹ Duật",
    "Đường M1", "Đường số 40", "Hoàng Văn Hợp", "Tạ Quang Bửu",
    "Đường Sinco", "Đường số 40A", "Hùng Vương", "Tân Hòa Đông",
    "2 Đường số 1", "2 Đường số 40B", "Hương lộ 13", "Tân Khai",
    "Đường số 10", "Đường số 42", "Hương lộ 2", "Tân Kỳ Tân Quý",
    "2 Đường số 11", "Đường số 42A", "Hương lộ 3", "Tân Sơn Nhì",
    "Đường số 11A", "Đường số 43", "Hương Lộ 5", "Tân Tạo",
    "Đường số 12", "Đường số 44", "Hương lộ 80", "Tây Lân",
    "Đường số 12A", "Đường số 46", "Kênh Nước Đen", "Tên Lửa",
    "2 Đường số 13", "Đường số 46A", "Khiếu Năng Tỉnh", "Thạch Lam",
    "2 Đường số 13A", "Đường số 47", "Khu Y Tế Kỹ Thuật Cao", "Thăng Long",
    "Đường số 13C", "Đường số 47C", "Kinh Dương Vương", "Thoại Ngọc Hầu",
    "2 Đường số 14", "Đường số 48", "Lâm Hoành", "Tỉnh Lộ 10",
    "Đường số 14A", "Đường số 48A", "Lê Cơ", "Tỉnh Lộ 13",
    "Đường số 14B", "Đường số 48B", "Lê Công Phép", "Tỉnh lộ 8",
    "Đường số 15", "Đường số 49", "Lê Đình Cẩn", "Trần Đại Nghĩa",
    "Đường số 16", "Đường số 49A", "Lê Đình Dương", "Trần Thanh Mai",
    "Đường số 16A", "Đường số 49B", "Lê Lợi", "Trần Thanh Mại",
    "Đường số 16B", "Đường số 49C", "Lê Ngung", "Trương Phước Phan",
    "Đường số 17", "Đường số 4A", "Lê Tấn Bê", "Vành Đai Trong",
    "Đường số 17A", "Đường số 4C", "Lê Thúc Hoạch", "Vĩnh Lộc",
    "Đường số 17B", "Đường số 5", "Lê Trọng Tấn", "Vĩnh Lộc B",
    "Đường số 18", "Đường số 50", "Lê Văn Quế", "Võ Văn Kiệt",
    "Đường số 18A", "Đường số 504", "Lê Văn Quới", "Võ Văn Vân",
    "Đường số 18B", "Đường số 50A"]
streets_district_phunhuan = [
    "Bạch Đằng", "Hoa Huệ", "Mai Văn Ngọc", "Phan Đình Phùng",
    "Cao Thắng", "Hoa Lan", "Mai Văn Nguyễn", "Phan Tây Hồ",
    "Cầm Bá Thước", "Hoa Mai", "Nguyễn Công Hoan", "Phan Xích Long",
    "Cô Bắc", "Hoa Phượng", "Nguyễn Đình Chính", "Phổ Quang",
    "Cô Giang", "Hoa Sứ", "Nguyễn Đình Chiểu", "Phùng Văn Cung",
    "Cù Lao", "Ký Con", "Nguyễn Kiệm", "Tân Cảnh",
    "Đào Duy Anh", "Hoàng Diệu", "Nguyễn Thái Sơn", "Thích Quảng Đức",
    "Đào Duy Từ", "Hoàng Minh Giám", "Nguyễn Thị Huỳnh", "Trần Cao Vân",
    "Đặng Thai Mai", "Hoàng Văn Thụ", "Nguyễn Thượng Hiền", "Trần Hữu Trang",
    "Đặng Văn Ngữ", "Hồ Văn Huê", "Nguyễn Trọng Tuyển", "Trần Kế Xương",
    "Đoàn Thị Điểm", "Hồng Hà", "Nguyễn Văn Đậu", "Trần Khắc Chân",
    "Hoa Cau", "Huỳnh Văn Bánh", "Nguyễn Văn Trỗi", "Trần Quang Diệu",
    "Hoa Cúc", "Lam Sơn", "Nhiêu Tứ", "Trương Đăng Quế",
    "Hoa Đào", "Lê Tư Tài", "Nội Bộ", "Trương Quốc Dung",
    "Hoa Hồng", "Lê Văn Sĩ", "Phan Đăng Lưu", "Trường Sa"
]
streets_district_govap = [
    "An Hội", "Đường số 30", "Huỳnh Văn Nghệ", "Nguyễn Văn Nghi",
    "An Nhơn", "Đường số 31", "Lê Đức Thọ", "Phạm Huy Thông",
    "Bùi Quang Là", "Đường số 32", "Lê Hoàng Phái", "Phạm Ngũ Lão",
    "Cây Trâm", "Đường số 35", "Lê Lai", "Phạm Văn Bạch",
    "Đỗ Thúc Tịnh", "Đường số 38", "Lê Lợi", "Phạm Văn Chiêu",
    "Đường 26 Tháng 3", "Đường số 4", "Lê Quang Định", "Phạm Văn Đồng",
    "Dương Quảng Hàm", "Đường số 43", "Lê Thị Hồng", "Phan Huy Ích",
    "Đường số 1", "Đường số 45", "Lê Văn Thọ", "Phan Văn Trị",
    "Đường số 10", "Đường số 46", "Lê Văn Trị", "Phùng Văn Cung",
    "Đường số 11", "Đường số 47", "Lương Ngọc Quyến", "Quang Trung",
    "Đường số 12", "Đường số 5", "Lý Thường Kiệt", "Tân Sơn",
    "Đường số 13", "Đường số 50", "Nguyễn Bỉnh Khiêm", "Tân Thọ",
    "Đường số 14", "Đường số 51", "Nguyễn Du", "Thích Bửu Đăng",
    "Đường số 15", "Đường số 53", "Nguyễn Duy Cung", "Thiên Hộ Dương",
    "Đường số 17", "Đường số 55", "Nguyên Hồng", "Thống Nhất",
    "Đường số 18", "Đường Số 56", "Nguyễn Hữu Thọ", "Thông Tây Hội",
    "Đường số 19", "Đường số 57", "Nguyễn Huy Điển", "Tô Ngọc Vân",
    "Đường số 2", "Đường số 58", "Nguyễn Kiệm", "Trần Bá Giao",
    "Đường số 20", "Đường số 59", "Nguyễn Oanh", "Trần Bình Trọng",
    "Đường số 21", "Đường số 6", "Nguyễn Thái Sơn", "Trần Phú Cương",
    "Đường số 22", "Đường số 7", "Nguyễn Thị Nhỏ", "Trần Quốc Tuấn",
    "Đường số 23", "Đường số 8", "Nguyễn Thượng Hiền", "Trần Thị Nghĩ",
    "Đường số 24", "Đường số 9", "Nguyễn Tư Giản", "Trưng Nữ Vương",
    "Đường số 25", "Hạnh Thông", "Nguyễn Tuân", "Trương Đăng Quế",
    "Đường số 27", "Hạnh Thông Tây", "Nguyễn Văn Bảo", "Trương Minh Giảng",
    "Đường số 28", "Hoàng Hoa Thám", "Nguyễn Văn Công", "Trương Minh Ký",
    "Đường số 29", "Hoàng Minh Giám", "Nguyễn Văn Dung", "Tú Mỡ",
    "Đường số 3", "Huỳnh Khương An", "Nguyễn Văn Lượng"
]
streets_district_thuduc = [
    "Bà Giang", "2 Đường số 24", "Đường số 6", "Nguyễn Khuyến",
    "Bác Ái", "Đường số 25", "Đường số 7", "Nguyễn Văn Bá",
    "Bình Chiểu", "Đường số 26", "Đường số 8", "Nguyễn Văn Lịch",
    "Bình Phú", "Đường số 27", "Đường số 9", "Phạm Văn Đồng",
    "Bồi Hoàn", "Đường số 28", "Dương Văn Cam", "Phú Châu",
    "Cây Keo", "Đường số 29", "Einstein", "Phượng Vĩ",
    "Chân Lý", "Đường số 3", "Gò Dưa", "Quốc Lộ 13",
    "Chu Mạnh Trinh", "Đường số 30", "Hàn Thuyên", "Quốc Lộ 1A",
    "Chương Dương", "Đường số 31", "Hiệp Bình", "Quốc Lộ 1K",
    "Công Lý", "Đường số 32", "Hồ Văn Tư", "Quy Đức",
    "Dân Chủ", "Đường số 33", "Hòa Bình", "Rạch Lùng",
    "Đặng Thị Rành", "Đường số 34", "Hoàng Diệu", "Tam Bình",
    "Đặng Văn Bi", "Đường số 35", "Hoàng Diệu 2", "Tam Châu",
    "Đào Trinh Nhất", "Đường số 36", "Hồng Đức", "Tam Hà",
    "Đoàn Công Hớn", "Đường số 37", "Hữu Nghị", "Tâm Tâm Xã",
    "Đoàn Kết", "Đường số 38", "Kha Vạn Cân", "Thống Nhất",
    "Đường số 1", "Đường số 39", "Khổng Tử", "Tỉnh lộ 42",
    "Đường số 10", "Đường số 4", "Khu làng Đại Học", "Tỉnh lộ 43",
    "Đường số 11", "Đường số 40", "Lam Sơn", "Tỉnh Lộ 44",
    "Đường số 12", "Đường số 41", "Lê Quý Đôn", "Tô Ngọc Vân",
    "Đường số 13", "Đường số 42", "Lê Thị Hoa", "Tô Vĩnh Diện",
    "Đường số 14", "Đường số 43", "Lê Văn Chí", "Trần Văn Nữa",
    "Đường số 147", "Đường số 44", "Lê Văn Ninh", "Trịnh Phong Đán",
    "Đường số 15", "Đường số 45", "Lê Văn Tách", "Trường Thọ",
    "Đường số 16", "Đường số 46", "Linh Đông", "Truông Tre",
    "Đường số 17", "Đường số 47", "Linh Trung", "Trương Văn Ngư",
    "2 Đường số 18", "Đường số 48", "Linh Xuân", "Ụ Ghe",
    "Đường số 19", "Đường số 49", "Lương Khải Siêu", "Võ Tiên Sư",
    "Đường số 2", "Đường số 5", "Lý Tế Xuyên", "Võ Văn Ngân",
    "Đường số 20", "Đường số 50", "Ngô Chí Quốc", "Xa Lộ Hà Nội",
    "Đường số 21", "Đường số 51", "Nguyễn An Ninh", "Xuân Hiệp",
    "Đường số 22", "2 Đường số 52", "Nguyễn Bá Luật",
    "2 Đường số 23", "Đường số 53", "Nguyễn Công Trứ"
]
streets_district_cuchi = [
    "An Nhơn Tây", "Đường 101", "Lê Thị Siêng", "Nhuận Đức",
    "An Phú", "Đường làng số 4", "Lê Thọ Xuân", "Ninh Tốn",
    "Ấp Bến Đò 1", "Đường số 11", "Lê Vĩnh Huy", "Ông Ích Đường",
    "Bà Nhép", "Đường số 181", "Liên Ấp Hội Thạnh", "Phạm Hữu Tâm",
    "Bà Thiên", "Đường số 21", "Liên Ấp Hội Thạnh - Chợ - An Bình", "Phạm Phú Tiết",
    "Bàu Lách", "Đường số 35", "Liên xã Bàu Hưng Lợi", "Phạm Văn Chèo",
    "Bàu Trăm", "Đường số 366", "Liên Xã Phước Vĩnh An - Phạm Văn Cội", "Phan Thị Hổi",
    "Bàu Tre", "Đường số 39", "Liên xã Trung Lập - Sa Nhỏ", "Quốc Lộ 22",
    "Bến Cỏ", "Đường số 40", "Liêu Bình Hương", "Ranh Khu Công Nghiệp",
    "Bến Đình", "Đường số 41", "Lưu Khai Hồng", "Sông Lu",
    "Bến Súc", "Đường số 42", "Ngô Tri Hòa", "Suối Lội",
    "Bến Than", "Đường số 456", "Nguyễn Đại Năng", "Tam Tân",
    "Bình Mỹ", "Đường số 490", "Nguyễn Đình Huân", "Tân Phú Trung",
    "Bốn Phú", "Đường số 5", "Nguyễn Giao", "Tân Thông Hội",
    "Bùi Thị Điệt", "Đường số 99", "Nguyễn Kim Cương", "Tỉnh Lộ 15",
    "Cá Lăng", "Giáp Hải", "Nguyễn Phong Sắc", "Tỉnh lộ 2",
    "Can Trường", "Giồng Cát", "Nguyễn Phúc Trú", "Tỉnh lộ 6",
    "Cây Bài", "Hà Văn Lao", "Nguyễn Thị Lắm", "Tỉnh Lộ 7",
    "Cây Da", "Hiệp Bình", "Nguyễn Thị Láng", "Tỉnh lộ 8",
    "Cây Gỗ", "Hồ Văn Tăng", "Nguyễn Thị Lắng", "Tỉnh lộ 9",
    "Cây Gỏ", "Hồ Văn Tắng", "Nguyễn Thị Nê", "Trần Thị Ngần",
    "Cây Trắc", "Hoàng Bá Huân", "Nguyễn Thị Rành", "Trần Tử Bình",
    "Cây Trôm", "Hương lộ 10", "Nguyễn Thị Rư", "Trần Văn Chẩm",
    "Cây Trôm - Mỹ Khánh", "Hương lộ 2", "Nguyễn Thị Triệu", "Trung An",
    "Đào Văn Thử", "Hương lộ 22", "Nguyễn Văn Khạ", "Trương Thị Kiện",
    "Đinh Chương Dương", "Hương Lộ 4", "Nguyễn Văn Ni", "Võ Thị Hồng",
    "Đình Kiến", "Huỳnh Minh Mương", "Nguyễn Văn Ơn", "Võ Văn Bích",
    "Đỗ Đăng Tuyển", "Huỳnh Thị Bằng", "Nguyễn Văn Tỳ", "Võ Văn Điều",
    "Đỗ Đình Nhân", "Huỳnh Văn Cọ", "Nguyễn Văn Xơ", "Vũ Duy Chí",
    "Đỗ Ngọc Du", "Kim Cương", "Nguyễn Viết Xuân", "Vũ Tụ",
    "Đỗ Quang Cơ", "Lê Minh Nhựt", "Nhữ Tiến Hiền", "Vườn Thước"
]
streets_district_hocmon = [
    "Ấp Dân Thắng 1", "Đường Tuyến 5", "Phạm Văn Sáng", "Tuyến Ống Nước Sạch",
    "Ấp Dân Thắng 2", "Đường Tuyến 9", "Phan Văn Đối", "Vạn Hạnh 1",
    "Ấp Đình 2", "Giác Đạo", "Phan Văn Hớn", "Vạn Hạnh 3",
    "Ấp Đình 4", "Hà Nội", "Quang Trung", "Vạn Hạnh 4",
    "Ấp Đông", "Hàn Quốc", "2 Quốc Lộ 1A", "Vành đai 3",
    "Ấp Mỹ Hòa I", "Hậu Lân", "Quốc Lộ 22", "Võ Thị Hồi",
    "Ấp Nam Thới", "Hậu Lân - Bà Điểm", "Rạch Hóc Môn", "Võ Văn Bích",
    "Ấp Tam Đông", "Hồ Ngọc Cẩn", "Rỗng Bàng", "Xuân Thới 15",
    "Ấp Tây Bắc Lân", "Hương Lộ 60", "Song Hành", "Xuân Thới 2",
    "Ấp Thông Nhất 2 - Nhị Tân 1", "Hương Lộ 60B", "Song Hành Quốc Lộ 22", "Xuân Thới 23",
    "Ấp Tiền Lân", "Hương Lộ 80B", "Tam Đông", "Xuân Thới 3",
    "Bà Điểm", "Khu Phố 1-01", "Tân Hiệp", "Xuân Thới 5",
    "Bà Điểm 2", "Khu Phố 1-02", "Tân Hiệp 14", "Xuân Thới 6",
    "Bà Điểm 5", "Khu Phố 1-03", "Tân Hiệp 15", "Xuân Thới 7",
    "Bà Điểm 6", "Khu Phố 2-01", "Tân Hiệp 16", "Xuân Thới 8",
    "Bà Điểm 7", "Khu Phố 2-02", "Tân Hiệp 31", "Xuân Thới 9",
    "Bà Điểm 8", "Khu Phố 3-01", "Tân Hiệp 4", "Xuân Thới Đông 2",
    "Bà Triệu", "Lê Lai", "Tân Hiệp 6", "Xuân Thới Sơn 1",
    "Bùi Chu", "Lê Lợi", "Tân Hiệp 7", "Xuân Thới Sơn 16",
    "Bùi Công Trừng", "Lê Thị Hà", "Tân Xuân 1", "Xuân Thới Sơn 2",
    "Bùi Văn Ngữ", "Lê Văn Khương", "Tân Xuân 2", "Xuân Thới Sơn 20C",
    "Chu Mạnh Trinh", "Liên Ấp 1-4", "Tân Xuân 6", "Xuân Thới Sơn 21",
    "Đặng Công Bình", "Liên Ấp 3-7", "Thái Bình", "Xuân Thới Sơn 22",
    "Đặng Thúc Vịnh", "Liên Ấp 5-7", "Thành Ủy", "Xuân Thới Sơn 26",
    "Đặng Văn Mười", "Liên Ấp Nam Thới - Thới Tứ", "Thiên Quang", "Xuân Thới Sơn 27",
    "Đỗ Văn Dậy", "Liên Ấp Thới Tứ Trung Đông", "Thới Tam Thôn 3", "Xuân Thới Sơn 37",
    "Đồng Bà Canh", "Liên Ấp: 2-6-7", "Thới Tam Thôn 6", "Xuân Thới Sơn 38",
    "Đông Lân", "Liên Xã Tân Hiệp", "Thới Tây", "Xuân Thới Sơn 4",
    "Đồng Tâm", "Liên Xã Tân Thới Nhì - Thị Trấn", "Thới Tây - Tân Hiệp", "Xuân Thới Sơn 5",
    "Đông Thạnh 2", "Liên Xã Thị Trấn - Tân Hiệp", "Thới Tứ", "Xuân Thới Sơn 6",
    "Đông Thạnh 2-5", "Liên Xã Thị Trấn - Thới Tam Thôn", "Thương Mại 1", "Xuân Thới Sơn 8",
    "Đông Thạnh 3", "Liên Xã Thới Tam Thôn - Đông Thạnh", "Thương Mại 3", "Xuân Thới Sơn A",
    "Đông Thạnh 4", "Lý Nam Đế", "Tô Ký", "Xuân Thới Thượng",
    "Đông Thạnh 4-2", "Lý Thường Kiệt", "Trần Bình Trọng", "Xuân Thới Thượng 15",
    "Đông Thạnh 5", "Mỹ Huề", "Trần Khắc Chân", "Xuân Thới Thượng 17",
    "Đông Thạnh 7", "Nam Lân", "Trần Văn Mười", "Xuân Thới Thượng 23",
    "Dương Công Khi", "Nam Thới 1", "Trịnh Thị Miếng", "Xuân Thới Thượng 24",
    "Đường số 12", "Nam Thới 2", "Trung Đông 11", "Xuân Thới Thượng 26",
    "Đường số 14", "Ngô Quyền", "Trung Đông 12", "Xuân Thới Thượng 4",
    "Đường số 17", "Nguyễn Ảnh Thủ", "Trung Đông 7", "Xuân Thới Thượng 5",
    "Đường số 2", "Nguyễn Hữu Cầu", "Trung Đông 8", "Xuân Thới Thượng 59",
    "Đường số 3", "Nguyễn Thị Rành", "Trung Lân 1", "Xuân Thới Thượng 6",
    "Đường số 5", "Nguyễn Thị Sóc", "Trung Mỹ", "Xuân Thới Thượng 7",
    "Đường số 6", "Nguyễn Thị Thử", "Trưng Nữ Vương", "Xuân Thới Thượng 8",
    "Đường số 7", "Nguyễn Văn Bứa", "Trưng Vương 3", "Xuân Thới Thượng 9",
    "Đường số 8", "Ống Nước", "Tuyến ấp 1"
]
streets_district_binhchanh = [
    "An Hạ", "Đường số 1", "Đường số 9", "Nguyễn Tri Phương",
    "An Phú Tây", "Đường số 10", "2 Đường số 9A", "Nguyễn Văn Bứa",
    "An Phú Tây - Hưng Long", "Đường số 10A", "Đường T12", "Nguyễn Văn Cừ",
    "Ấp Hưng Lân", "Đường số 10B", "Đường T4", "2 Nguyễn Văn Linh",
    "Bà Cả", "Đường số 11", "Giao Thông Hào Ấp 3", "Nguyễn Văn Long",
    "Bà Điểm", "Đường số 11A", "Hoàng Đạo Thúy", "Nguyễn Văn Thê",
    "Bà Thao", "Đường số 12", "Hoàng Phan Thái", "Nguyễn Văn Thời",
    "Bàu Gốc", "Đường số 13", "Hóc Hữu", "Nữ Dân Công",
    "Bảy Tấn", "Đường số 13A", "Hưng Long", "Phạm Hùng",
    "Bến Lội", "Đường số 14", "Hưng Nhơn", "Phạm Văn Sáng",
    "Bình Hưng", "Đường số 15", "Hùng Vương", "Phan Tấn Mười",
    "Bình Minh", "Đường số 16", "Hương lộ 11", "Quách Điêu",
    "Bình Trường", "Đường số 17", "Hương lộ 80", "Quốc Lộ 13",
    "Bờ Huệ", "Đường số 18", "Huỳnh Bá Chánh", "Quốc Lộ 1A",
    "Bờ Nhà Thờ", "Đường số 18A", "Huỳnh Văn Trí", "Quốc Lộ 50",
    "Bờ Xe Lam", "Đường số 18B", "Kênh 7", "Quy Đức",
    "Bông Văn Dĩa", "Đường số 19", "Khiếu Năng Tỉnh", "Rạch Ông Cốm",
    "Bùi Thanh Khiết", "2 Đường số 1A", "Khoa Đông", "Tân Kiên",
    "Bùi Văn Sự", "Đường số 1B", "Khuất Văn Bức", "Tân Liêm",
    "Cái Trung", "Đường số 1C", "Kinh Liên Vùng", "Tân Liễu",
    "Cao Tốc Trung Lương", "Đường số 1D", "Kinh Rau Răm", "Tân Long",
    "Cây Bàng", "Đường số 1E", "Kinh Sáu Ánh", "Tân Nhiểu",
    "Cây Cám", "Đường số 1F", "Lại Hùng Cường", "Tân Quý Tây",
    "Chánh Hưng", "2 Đường số 2", "Láng Le - Bàu Cò", "Tân Túc",
    "Công Nghệ Mới", "Đường số 20", "Lê Bá Trinh", "Tập Đoàn 16",
    "Đá Đỏ", "Đường số 21", "Lê Chính Đáng", "Thanh Niên",
    "Đa Phước", "Đường số 22", "Lê Đình Chi", "Thế Lữ",
    "Dân Công Hỏa Tuyến", "Đường số 24", "Lê Minh Xuân", "Thích Thiện Hòa",
    "Đê Rạch Ông Đồ", "Đường số 26", "Liên Ấp 1", "Thiên Giang",
    "Đê Ranh", "Đường số 27", "Liên Ấp 1-2", "Thới Hòa",
    "Đê Số 2", "Đường số 2A", "Liên Ấp 1-2-3", "Tỉnh Lộ 10",
    "Đinh Đức Thiện", "Đường số 2B", "Liên Ấp 2", "Tỉnh Lộ 10B",
    "Đoàn Nguyễn Tuân", "2 Đường số 3", "Liên Ấp 2-3", "Trầm Lầy 1",
    "Đường Ấp 2", "Đường số 3A", "Liên Ấp 2-3-4", "Trần Đại Nghĩa",
    "Đường Ấp 4", "2 Đường số 4", "2 Liên Ấp 2-6", "Trần Hải Phụng",
    "Đường C3", "Đường số 4A", "Liên Ấp 3", "Trần Văn Giàu",
    "Đường Chùa", "Đường số 4B", "Liên Ấp 3-4", "Trịnh Như Khuê",
    "Dương Đình Cúc", "Đường số 5", "Liên Ấp 3-4-5", "Trịnh Quang Nghị",
    "Đường Kênh A", "Đường số 5A", "Liên Ấp 4-5", "Trương Văn Đa",
    "Đường Kênh B", "Đường số 5B", "Liên Ấp 5-6", "Vĩnh Lộc",
    "Đường Kênh C", "Đường số 5C", "Liên Ấp 6", "Vĩnh Lộc B",
    "Đường Kinh 10", "2 Đường số 6", "Linh Hòa", "Võ Hữu Lợi",
    "Đường Kinh 5", "Đường số 6A", "Lô 2", "Võ Văn Kiệt",
    "Đường Kinh 7", "Đường số 6B", "Lương Ngang", "Võ Văn Vân",
    "Đường Kinh 8", "Đường số 6C", "Mai Bá Hương", "Vườn Thơm",
    "Đường Kinh 9", "Đường số 6D", "Miếu Ông Đá", "Xã Hai",
    "Đường Kinh A", "Đường số 7", "Nguyễn Cửu Phú", "Xóm Dầu",
    "Đường Kinh C", "Đường số 7A", "Nguyễn Đình Kiên", "Xóm Giữa",
    "Đường Kinh số 7", "Đường số 8", "Nguyễn Hữu Trí", "Xóm Hố",
    "Đường Kinh T11", "Đường số 8A", "Nguyễn Thị Thập",
    "Đường Kinh T12", "Đường số 8B", "Nguyễn Thị Thọ",
    "Đường Kinh T14", "Đường số 8C", "Nguyễn Thị Tú"
]
streets_district_nhabe = [
    "Bà Cả", "2 Huỳnh Tấn Phát", "Nguyễn Văn Thọ",
    "Bờ Tây", "Khu Trung Tâm Huyện", "Nhơn Đức",
    "Chánh Hưng", "Lê Văn Lương", "Nội Bộ Khu Cán Bộ Công Nhân Viên Huyện",
    "Chánh Hưng Nối Dài", "Liên Ấp 2-3", "Nội Bộ Khu Tái Định Cư KCN Hiệp Phước",
    "Đặng Nhữ Lâm", "Liên Ấp 3-4", "Nội Bộ Khu Tái Định Cư Khu Vực Cầu Bà Sáu",
    "Đào Sư Tích", "Long Thới", "Nội Bộ Khu Tái Định Cư Phước Kiến Giai Đoạn I",
    "Đào Tông Nguyên", "Long Thới - Nhơn Đức", "Phạm Hữu Lầu",
    "Đào Xuân Tích", "Nguyễn Bình", "Phan Văn Bảy",
    "Đường 20D", "Nguyễn Hữu Thọ", "Phú Xuân",
    "Dương Cát Lợi", "Nguyễn Lương Bằng", "Vạn Phát Hưng",
    "Đường số 6", "Nguyễn Văn Linh",
    "Hương Lộ 34B", "Nguyễn Văn Tạo"
]

district_hcm_mapping = HCM = {
    "Quận 1": streets_district1,
    "Quận 2": streets_district2,
    "Quận 3": streets_district3,
    "Quận 4": streets_district4,
    "Quận 5": streets_district5,
    "Quận 6": streets_district6,
    "Quận 7": streets_district7,
    "Quận 8": streets_district8,
    "Quận 9": streets_district9,
    "Quận 10": streets_district10,
    "Quận 11": streets_district11,
    "Quận 12": streets_district12,
    "Quận Bình Thạnh": streets_district_binhthanh,
    "Quận Tân Phú": streets_district_tanphu,
    "Quận Tân Bình": streets_district_tanbinh,
    "Quận Bình Tân": streets_district_binhtan,
    "Quận Phú Nhuận": streets_district_phunhuan,
    "Quận Gò Vấp": streets_district_govap,
    "Thành phố Thủ Đức": streets_district_thuduc,
    "Huyện Củ Chi": streets_district_cuchi,
    "Hóc Môn": streets_district_hocmon,
    "Bình Chánh": streets_district_binhchanh,
    "Nhà Bè": streets_district_nhabe
}




